version: '3.8'
services:
  service-registry:
    image: service-registry
    container_name: service-registry
    build:
      context: /home/cash/Downloads/Ecommerce/Service-Registry
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  api-gateway:
    image: api-gw
    container_name: api-gw
    build:
      context: ./api-gateway
    depends_on:
      - service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8084:8084"
    networks:
      - microservices-network

  order-service:
    image: order-service
    container_name: order-service
    build:
      context: ./order-service
    depends_on:
      - service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8082:8082"
    networks:
      - microservices-network

  product-service:
    image: product-service
    container_name: product-service
    build:
      context: ./product-service
    depends_on:
      - service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    ports:
      - "8081:8081"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
