spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
        - id: order-route
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**

      discovery:
        locator:
          enabled: true


  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka